# Generated by Django 4.0.4 on 2022-05-03 11:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', ckeditor_uploader.fields.RichTextUploadingField()),
                ('resources_need', ckeditor_uploader.fields.RichTextUploadingField()),
                ('challenges_faced_in_the_previous_quarter', ckeditor_uploader.fields.RichTextUploadingField()),
                ('how_the_challenges_can_be_addressed', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directorate', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=400, verbose_name='Job performed this month')),
                ('reasons', models.CharField(max_length=400, verbose_name='Reason, if no job performed')),
                ('attendance', models.CharField(max_length=400, verbose_name='Attendance at monthly meeting ')),
                ('absent', models.CharField(max_length=400, verbose_name='Reason, if absent')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
