# Generated by Django 4.0.4 on 2022-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0003_alter_evaluation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorate',
            name='challenges_faced_in_the_previous_quarter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='how_the_challenges_can_be_addressed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='plans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='resources_need',
            field=models.TextField(),
        ),
    ]
