# Generated by Django 4.0.4 on 2022-06-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0004_alter_directorate_challenges_faced_in_the_previous_quarter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorate',
            old_name='plans',
            new_name='plans_for_the_quarter',
        ),
        migrations.RenameField(
            model_name='directorate',
            old_name='resources_need',
            new_name='resources_needed',
        ),
    ]
